print('-'*80)
print('Morbid Predictions Program:')
print('Description: This program asks you for your current age and tells you the year that you will die (on average).')
print()
age= input('What is your age today? ')
age= int(age)
print('...thinking...')
print('...thinking...')
print('...thinking...')
print('You will die in the year...')
birth= 2018 - age
birth= int(birth)
answer= birth + 79
answer= int(answer)
print(answer)
